services:
  airflow-init:
    environment:
      DOCKER_URL: "docker.world-modelers:8375"
      DMC_LOCAL_DIR:
      MIXMASTA_VERSION:
    networks:
      - world-modelers
    volumes:
      - dmc-data-results:/results
      - dmc-data-mappers:/mappers
      - dmc-data-model_configs:/model_configs
  airflow-redis:
    environment:
      DOCKER_URL: "docker.world-modelers:8375"
      DMC_LOCAL_DIR:
      MIXMASTA_VERSION:
    networks:
      - world-modelers
  airflow-postgres:
    environment:
      DOCKER_URL: "docker.world-modelers:8375"
      DMC_LOCAL_DIR:
      MIXMASTA_VERSION:
    networks:
      - world-modelers
  airflow-scheduler:
    environment:
      DOCKER_URL: "docker.world-modelers:8375"
      DMC_LOCAL_DIR:
      MIXMASTA_VERSION:
    networks:
      - world-modelers
    volumes:
      - dmc-data-results:/results
      - dmc-data-mappers:/mappers
      - dmc-data-model_configs:/model_configs
  airflow-webserver:
    environment:
      DOCKER_URL: "docker.world-modelers:8375"
      DMC_LOCAL_DIR:
      MIXMASTA_VERSION:
    networks:
      - world-modelers
    volumes:
      - dmc-data-results:/results
      - dmc-data-mappers:/mappers
      - dmc-data-model_configs:/model_configs
  airflow-worker:
    environment:
      AIRFLOW_CONN_AWS_DEFAULT: aws://${AWS_ACCESS_KEY_ID}:${AWS_SECRET_ACCESS_KEY_ENCODED}@
      BUCKET: ${DMC_BUCKET}
      DOCKER_URL: "docker.world-modelers:8375"
      DMC_LOCAL_DIR:
      MIXMASTA_VERSION:
    networks:
      - world-modelers
    volumes:
      - dmc-data-results:/results
      - dmc-data-mappers:/mappers
      - dmc-data-model_configs:/model_configs
  flower:
    environment:
      DOCKER_URL: "docker.world-modelers:8375"
      DMC_LOCAL_DIR:
      MIXMASTA_VERSION:
    networks:
      - world-modelers
  app:
    command:
      - python3
      - manage.py
      - runserver
      - 0.0.0.0:8000
    env_file:
      - envfile
    networks:
      - world-modelers
  processor:
    env_file:
      - envfile
    networks:
      - world-modelers
  shorthand-app:
    env_file:
      - envfile
    environment:
      - DOJO_HOST
      - S3_ACCESS_KEY_ID
      - S3_SECRET_ACCESS_KEY
    networks:
      - world-modelers
  api:
    command:
      [
        "uvicorn",
        "server:api",
        "--host",
        "0.0.0.0",
        "--port",
        "80",
        "--reload",
        "--reload-dir",
        "src",
        "--log-config",
        "logging.yaml"
      ]
    volumes:
      - ./dojo/api:/api
    env_file:
      - envfile
    environment:
      - DOJO_URL
      - DMC_LOCAL_DIR
      - DMC_URL
      - DMC_PASSWORD
      - REDIS_HOST
      - DOCKERHUB_USER
      - DOCKERHUB_PWD
    networks:
      - world-modelers
  cato:
    command: -debug -pull-images=false
    build:
      context: ./clouseau
      dockerfile: cato/Dockerfile
    image: jataware/clouseau:cato-dev
    volumes:
      - ${PWD}/clouseau/claudine/server/settings.yaml:/home/app/cato/settings.yaml:rw
    env_file:
      - envfile
    environment:
      - DOCKERHUB_AUTH
    networks:
      - world-modelers
    depends_on:
      - redis
  kibana:
    env_file:
      - envfile
    networks:
      - world-modelers
  elasticsearch:
    env_file:
      - envfile
    networks:
      - world-modelers
  redis:
    env_file:
      - envfile
    networks:
      - world-modelers
  docker:
    env_file:
      - envfile
    networks:
      - world-modelers
    volumes:
      - dmc-data-results:/data/results
      - dmc-data-mappers:/data/mappers
      - dmc-data-model_configs:/data/model_configs
  phantom:
    build:
      context: ./phantom/
      dockerfile: Dockerfile.dev
    container_name: phantom
    env_file:
      - envfile
    volumes:
      - "./phantom/ui:/ui"
    expose:
      - 8080
    ports:
      - "8080:8080"
    command:
      - npx
      - webpack
      - serve
      - --mode
      - development
      - --config
      - ./webpack.config.dev.js
      - --host
      - 0.0.0.0
    networks:
      - world-modelers
  perm-fixer:
    build:
      context: ./perm-fixer/
    volumes:
      - dmc-data-results:/data/results
      - dmc-data-mappers:/data/mappers
      - dmc-data-model_configs:/data/model_configs
  rqworker:
    env_file:
      - envfile
    networks:
      - world-modelers
    depends_on:
      - redis

networks:
  world-modelers:
    driver: bridge
    name: world-modelers

volumes:
  dmc-data-results:
  dmc-data-mappers:
  dmc-data-model_configs:
