version: "3"
services:
  phantom:
    build:
      context: ./phantom/
      dockerfile: Dockerfile.dev
    container_name: phantom
    volumes:
      - "./phantom/ui:/ui"
    expose:
      - 8080
    ports:
      - "8080:8080"
    command:
      - npm
      - run
      - dev
