services:
  api:
    build:
      context: ./api/  
    command:
      [
        "uvicorn",
        "server:api",
        "--host",
        "0.0.0.0",
        "--port",
        "80",
        "--reload",
        "--reload-dir",
        "src",
        "--log-config",
        "logging.yaml"
      ]
    volumes:
      - ./api:/api
      - dataset-storage:/datasets
    environment:
      - DATA_ANNOTATION_URL
      - REDIS_HOST
      - DKG_URL
    networks:
      - data-annotation-stack
  redis:
    env_file:
      - envfile
    networks:
      - data-annotation-stack
  ui:
    build:
      context: ./ui/
      dockerfile: Dockerfile.dev
    container_name: ui
    env_file:
      - envfile
    environment:
      - DKG_URL
    volumes:
      - "./ui:/ui"
    expose:
      - 8080
    ports:
      - "8081:8080"
    command:
      - npx
      - webpack
      - serve
      - --mode
      - development
      - --config
      - ./webpack.config.dev.js
      - --host
      - 0.0.0.0
    networks:
      - data-annotation-stack
  rqworker:
    build:
      context: ./tasks/  
    env_file:
      - envfile
    networks:
      - data-annotation-stack
    depends_on:
      - redis
    volumes:
      - dataset-storage:/datasets

networks:
  data-annotation-stack:
    driver: bridge
    name: data-annotation-stack

volumes:
  dataset-storage:
