services:
  api:
    command:
      [
        "uvicorn",
        "server:api",
        "--host",
        "0.0.0.0",
        "--port",
        "80",
        "--reload",
        "--reload-dir",
        "src",
        "--log-config",
        "logging.yaml"
      ]
    volumes:
      - ./api:/api
      - dataset-storage:/datasets
    env_file:
      - envfile
    environment:
      - DOJO_URL
      - REDIS_HOST
    networks:
      - dojo-stack
    depends_on:
      elasticsearch:
        condition: service_healthy
  elasticsearch:
    env_file:
      - envfile
    networks:
      - dojo-stack
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - curl
        - --fail
        - http://localhost:9200/_cluster/health
      timeout: 10s
  redis:
    env_file:
      - envfile
    networks:
      - dojo-stack
  phantom:
    build:
      context: ./phantom/
      dockerfile: Dockerfile.dev
    container_name: phantom
    env_file:
      - envfile
    volumes:
      - "./phantom/ui:/ui"
    expose:
      - 8080
    ports:
      - "8081:8080"
    command:
      - npx
      - webpack
      - serve
      - --mode
      - development
      - --config
      - ./webpack.config.dev.js
      - --host
      - 0.0.0.0
    networks:
      - dojo-stack
  rqworker:
    env_file:
      - envfile
    networks:
      - dojo-stack
    depends_on:
      - redis
    volumes:
      - dataset-storage:/datasets

networks:
  dojo-stack:
    driver: bridge
    name: dojo-stack

volumes:
  dmc-data-results:
  dmc-data-mappers:
  dmc-data-model_configs:
  dataset-storage:
