version: '2.2'
services:
  rqworker:
    build: .
    container_name: data-annotation-rq-worker
    networks:
      - data-annotation-stack
    command:
      - rq
      - worker
      - --url
      - redis://${REDIS_HOST}:${REDIS_PORT}
      - high
      - default
      - low

networks:
  data-annotation-stack:
    driver: bridge
