apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
    - name: 9200-tcp
      port: 9200
      protocol: TCP
      targetPort: 9200 
  selector:
    co.elastic.terarium: elasticsearch
  type: LoadBalancer
status:
  loadBalancer: {}