apiVersion: v1
kind: Pod
metadata:
  labels:
    co.elastic.terarium: elasticsearch
  name: elasticsearch
spec:
  containers:
    - image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
      name: elasticsearch
      ports:
        - containerPort: 9200
          protocol: TCP
      resources: {}
      env:
        - name: discovery.type
          value: single-node
        - name: bootstrap.memory_lock
          value: "true"
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
  restartPolicy: Always
status: {}