apiVersion: v1
kind: Pod
metadata:
  labels:
    io.redis.terarium: redis
  name: redis
spec:
  containers:
    - image: :redis
      name: redis
      ports:
        - containerPort: 6379
          protocol: TCP
      resources: {}
  restartPolicy: Always
status: {}