version: "3"
services:

  phantom:
    image: jataware/phantom:dev
    container_name: phantom1
    ports:
      - 8080:80
    environment:
      API_HOST: ${PRIVATE_IP}
      WEBSOCKET_HOST: ${PRIVATE_IP}


