version: '2.2'
services:
  api:
    build: .
    container_name: data-annotation-api
    volumes:
      - ./:/api
    command:
      [
        "uvicorn",
        "server:api",
        "--host",
        "0.0.0.0",
        "--port",
        "80",
        "--reload",
        "--reload-dir",
        "src",
        "--log-config",
        "logging.yaml"
      ]
    ports:
      - 8000:80
    expose:
      - "8000"
    env_file:
      - envfile
    networks:
      - dojo

  redis:
    container_name: redis1
    image: redis
    ports:
      - 6379:6379
    networks:
      - dojo

volumes:
  dojo_esdata:
    driver: local

networks:
  dojo:
    driver: bridge
