name: Build

on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Lint
        run: make fmt

      - name: Build Containers
        run: make docker_build
