
name: js

on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        node: [ '15' ]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: npm install
        working-directory: ./app
        run: npm install
      - name: lint
        run: make npm_lint
      - name: npm build
        run: make npm_build

